import type { GeneratedImage, Project, BatchJob, AIModel, Template, Notification, TeamMember, ApiKey } from './types';

export const MOCK_IMAGES: GeneratedImage[] = [
  {
    id: 'img-1',
    url: 'https://images.pexels.com/photos/8107821/pexels-photo-8107821.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Futuristic cyberpunk woman with neon lights, ultra detailed, cinematic lighting, 8k resolution',
    negativePrompt: 'blurry, low quality, distorted',
    model: 'PixelForge Flux Pro',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    seed: 4829301,
    steps: 40,
    cfg: 7.5,
    style: 'Cinematic',
    generationTime: 12.4,
    credits: 8,
    createdAt: '2026-09-14T10:30:00Z',
    isFavorite: true,
    projectId: 'proj-1',
    tags: ['cyberpunk', 'portrait', 'neon'],
    width: 1536,
    height: 1024,
  },
  {
    id: 'img-2',
    url: 'https://images.pexels.com/photos/10109585/pexels-photo-10109585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Surreal abstract landscape with vibrant colors, digital render, mountains and sea, otherworldly',
    negativePrompt: 'blurry, artifacts, noise',
    model: 'PixelForge Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    seed: 1023948,
    steps: 35,
    cfg: 8.0,
    style: 'Fantasy',
    generationTime: 9.2,
    credits: 6,
    createdAt: '2026-09-14T09:15:00Z',
    isFavorite: false,
    projectId: 'proj-2',
    tags: ['landscape', 'fantasy', 'colorful'],
    width: 1024,
    height: 1024,
  },
  {
    id: 'img-3',
    url: 'https://images.pexels.com/photos/34921744/pexels-photo-34921744.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'High fashion editorial, woman in black dress, dramatic lighting, luxury brand aesthetic',
    negativePrompt: 'casual, low quality, overexposed',
    model: 'Realistic Vision',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    seed: 7381920,
    steps: 45,
    cfg: 6.5,
    style: 'Fashion',
    generationTime: 15.8,
    credits: 10,
    createdAt: '2026-09-14T08:45:00Z',
    isFavorite: true,
    projectId: 'proj-3',
    tags: ['fashion', 'editorial', 'luxury'],
    width: 1024,
    height: 1536,
  },
  {
    id: 'img-4',
    url: 'https://images.pexels.com/photos/36339062/pexels-photo-36339062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Elegant face cream container on minimalist pedestals, product photography, white background',
    model: 'PixelForge Fast',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    seed: 2847563,
    steps: 30,
    cfg: 7.0,
    style: 'Product Photography',
    generationTime: 6.3,
    credits: 4,
    createdAt: '2026-09-13T16:20:00Z',
    isFavorite: false,
    projectId: 'proj-1',
    tags: ['product', 'minimal', 'beauty'],
    width: 1024,
    height: 1024,
  },
  {
    id: 'img-5',
    url: 'https://images.pexels.com/photos/13568045/pexels-photo-13568045.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: '3D abstract purple mountainous terrain, smooth dynamic textures, sci-fi environment',
    model: 'Flux Pro',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    seed: 9182736,
    steps: 50,
    cfg: 9.0,
    style: 'Sci-Fi',
    generationTime: 18.1,
    credits: 12,
    createdAt: '2026-09-13T14:05:00Z',
    isFavorite: true,
    projectId: 'proj-2',
    tags: ['3d', 'abstract', 'sci-fi'],
    width: 1536,
    height: 1024,
  },
  {
    id: 'img-6',
    url: 'https://images.pexels.com/photos/28481966/pexels-photo-28481966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Perfume bottle with dramatic hand shadows, mysterious and artistic, luxury fragrance',
    model: 'PixelForge Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    seed: 5647382,
    steps: 40,
    cfg: 7.5,
    style: 'Product Photography',
    generationTime: 11.7,
    credits: 8,
    createdAt: '2026-09-13T11:30:00Z',
    isFavorite: false,
    projectId: 'proj-1',
    tags: ['product', 'perfume', 'luxury'],
    width: 1024,
    height: 1024,
  },
  {
    id: 'img-7',
    url: 'https://images.pexels.com/photos/2058172/pexels-photo-2058172.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Minimalist cylindrical building, architectural photography, clear blue sky, modern design',
    model: 'Cinematic XL',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    seed: 3847291,
    steps: 38,
    cfg: 8.5,
    style: 'Architecture',
    generationTime: 14.2,
    credits: 10,
    createdAt: '2026-09-12T15:45:00Z',
    isFavorite: false,
    projectId: 'proj-4',
    tags: ['architecture', 'minimal', 'modern'],
    width: 1536,
    height: 1024,
  },
  {
    id: 'img-8',
    url: 'https://images.pexels.com/photos/8108412/pexels-photo-8108412.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Futuristic man in neon-lit environment, cyberpunk style, sunglasses, ultra detailed',
    model: 'PixelForge Flux Pro',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    seed: 6182749,
    steps: 42,
    cfg: 7.0,
    style: 'Cinematic',
    generationTime: 13.5,
    credits: 9,
    createdAt: '2026-09-12T12:10:00Z',
    isFavorite: true,
    projectId: 'proj-3',
    tags: ['cyberpunk', 'portrait', 'neon'],
    width: 1024,
    height: 1536,
  },
  {
    id: 'img-9',
    url: 'https://images.pexels.com/photos/23191211/pexels-photo-23191211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Dynamic abstract painting with neon colors, vivid visual impact, digital art style',
    model: 'Illustration Pro',
    resolution: '2048 × 1152',
    aspectRatio: '16:9',
    seed: 8472910,
    steps: 35,
    cfg: 6.0,
    style: 'Illustration',
    generationTime: 20.3,
    credits: 14,
    createdAt: '2026-09-12T09:30:00Z',
    isFavorite: false,
    projectId: 'proj-5',
    tags: ['abstract', 'colorful', 'digital-art'],
    width: 2048,
    height: 1152,
  },
  {
    id: 'img-10',
    url: 'https://images.pexels.com/photos/8474976/pexels-photo-8474976.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Astronauts exploring Mars desert landscape, sci-fi environment, cinematic photography',
    model: 'Cinematic XL',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    seed: 1928374,
    steps: 50,
    cfg: 8.0,
    style: 'Sci-Fi',
    generationTime: 22.1,
    credits: 16,
    createdAt: '2026-09-11T17:00:00Z',
    isFavorite: true,
    projectId: 'proj-2',
    tags: ['sci-fi', 'space', 'cinematic'],
    width: 1536,
    height: 1024,
  },
  {
    id: 'img-11',
    url: 'https://images.pexels.com/photos/5611592/pexels-photo-5611592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Beautiful serene portrait, white outfit, bare shoulders, dramatic smoke effects',
    model: 'Realistic Vision',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    seed: 4728192,
    steps: 45,
    cfg: 7.5,
    style: 'Photorealistic',
    generationTime: 16.4,
    credits: 11,
    createdAt: '2026-09-11T13:20:00Z',
    isFavorite: false,
    projectId: 'proj-3',
    tags: ['portrait', 'dramatic', 'studio'],
    width: 1024,
    height: 1536,
  },
  {
    id: 'img-12',
    url: 'https://images.pexels.com/photos/30547578/pexels-photo-30547578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Futuristic digital grid with glowing red and black elements, 3D illustration',
    model: 'Flux Dev',
    resolution: '2048 × 1080',
    aspectRatio: '16:9',
    seed: 9847261,
    steps: 55,
    cfg: 9.5,
    style: 'Concept Art',
    generationTime: 25.7,
    credits: 18,
    createdAt: '2026-09-11T10:45:00Z',
    isFavorite: true,
    projectId: 'proj-5',
    tags: ['digital', '3d', 'abstract'],
    width: 2048,
    height: 1080,
  },
  {
    id: 'img-13',
    url: 'https://images.pexels.com/photos/8882645/pexels-photo-8882645.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Dynamic abstract painting, bold brushstrokes in vibrant orange, purple, and blue',
    model: 'Illustration Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    seed: 3748291,
    steps: 30,
    cfg: 6.5,
    style: 'Oil Painting',
    generationTime: 8.9,
    credits: 6,
    createdAt: '2026-09-10T16:30:00Z',
    isFavorite: false,
    projectId: 'proj-5',
    tags: ['painting', 'abstract', 'colorful'],
    width: 1024,
    height: 1024,
  },
  {
    id: 'img-14',
    url: 'https://images.pexels.com/photos/7688749/pexels-photo-7688749.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Woman interacting with robotic hands through neon mesh, cyberpunk atmosphere',
    model: 'PixelForge Flux Pro',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    seed: 6182930,
    steps: 48,
    cfg: 8.0,
    style: 'Cinematic',
    generationTime: 17.3,
    credits: 12,
    createdAt: '2026-09-10T14:15:00Z',
    isFavorite: true,
    projectId: 'proj-1',
    tags: ['cyberpunk', 'robot', 'neon'],
    width: 1536,
    height: 1024,
  },
  {
    id: 'img-15',
    url: 'https://images.pexels.com/photos/1816030/pexels-photo-1816030.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Modern building with glass and steel design, urban architecture, low angle view',
    model: 'Cinematic XL',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    seed: 5829174,
    steps: 40,
    cfg: 7.5,
    style: 'Architecture',
    generationTime: 12.8,
    credits: 9,
    createdAt: '2026-09-10T11:00:00Z',
    isFavorite: false,
    projectId: 'proj-4',
    tags: ['architecture', 'glass', 'urban'],
    width: 1024,
    height: 1536,
  },
  {
    id: 'img-16',
    url: 'https://images.pexels.com/photos/11515541/pexels-photo-11515541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Luxury perfume bottle on soft white fabric, elegant product photography, soft lighting',
    model: 'PixelForge Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    seed: 2748391,
    steps: 35,
    cfg: 7.0,
    style: 'Product Photography',
    generationTime: 10.2,
    credits: 7,
    createdAt: '2026-09-09T15:30:00Z',
    isFavorite: false,
    projectId: 'proj-1',
    tags: ['product', 'luxury', 'perfume'],
    width: 1024,
    height: 1024,
  },
  {
    id: 'img-17',
    url: 'https://images.pexels.com/photos/207130/pexels-photo-207130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Dreamlike mountain landscape illuminated by full moon, dramatic clouds, cinematic',
    model: 'Flux Pro',
    resolution: '2048 × 1152',
    aspectRatio: '16:9',
    seed: 8374829,
    steps: 52,
    cfg: 8.5,
    style: 'Fantasy',
    generationTime: 23.4,
    credits: 16,
    createdAt: '2026-09-09T12:45:00Z',
    isFavorite: true,
    projectId: 'proj-2',
    tags: ['landscape', 'moon', 'dramatic'],
    width: 2048,
    height: 1152,
  },
  {
    id: 'img-18',
    url: 'https://images.pexels.com/photos/33714925/pexels-photo-33714925.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Fashion model in black dress, red-lit studio, dramatic and modern editorial',
    model: 'Realistic Vision',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    seed: 1928374,
    steps: 44,
    cfg: 7.0,
    style: 'Fashion',
    generationTime: 15.1,
    credits: 10,
    createdAt: '2026-09-09T09:20:00Z',
    isFavorite: false,
    projectId: 'proj-3',
    tags: ['fashion', 'studio', 'editorial'],
    width: 1024,
    height: 1536,
  },
  {
    id: 'img-19',
    url: 'https://images.pexels.com/photos/8108483/pexels-photo-8108483.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Two stylish individuals in cyberpunk setting, futuristic fashion under neon lights',
    model: 'PixelForge Flux Pro',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    seed: 4729183,
    steps: 46,
    cfg: 8.0,
    style: 'Cinematic',
    generationTime: 16.8,
    credits: 12,
    createdAt: '2026-09-08T17:10:00Z',
    isFavorite: true,
    projectId: 'proj-3',
    tags: ['cyberpunk', 'fashion', 'neon'],
    width: 1536,
    height: 1024,
  },
  {
    id: 'img-20',
    url: 'https://images.pexels.com/photos/30767251/pexels-photo-30767251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    prompt: 'Abstract 3D geometric shape with neon green glow, digital art, futuristic concept',
    model: 'Flux Dev',
    resolution: '1920 × 1080',
    aspectRatio: '16:9',
    seed: 7382910,
    steps: 60,
    cfg: 9.0,
    style: '3D',
    generationTime: 28.5,
    credits: 20,
    createdAt: '2026-09-08T14:00:00Z',
    isFavorite: false,
    projectId: 'proj-5',
    tags: ['3d', 'geometric', 'neon'],
    width: 1920,
    height: 1080,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'E-commerce Campaign',
    description: 'Product photography and marketing assets for Q4 launch',
    coverImage: 'https://images.pexels.com/photos/36339062/pexels-photo-36339062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 284,
    lastUpdated: '2026-09-14T10:30:00Z',
    owner: 'Himanshu',
    storage: '4.2 GB',
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 'proj-2',
    name: 'YouTube Thumbnails',
    description: 'Cinematic thumbnails for tech review channel',
    coverImage: 'https://images.pexels.com/photos/10109585/pexels-photo-10109585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 156,
    lastUpdated: '2026-09-13T15:20:00Z',
    owner: 'Himanshu',
    storage: '2.8 GB',
    color: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'proj-3',
    name: 'Character Design',
    description: 'Original character concepts for indie game project',
    coverImage: 'https://images.pexels.com/photos/8107821/pexels-photo-8107821.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 412,
    lastUpdated: '2026-09-12T11:45:00Z',
    owner: 'Himanshu',
    storage: '7.1 GB',
    color: 'from-pink-500 to-rose-600',
  },
  {
    id: 'proj-4',
    name: 'Architecture Concepts',
    description: 'Modern architectural visualization and concept art',
    coverImage: 'https://images.pexels.com/photos/2058172/pexels-photo-2058172.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 97,
    lastUpdated: '2026-09-11T09:00:00Z',
    owner: 'Himanshu',
    storage: '1.9 GB',
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'proj-5',
    name: 'Abstract Art Series',
    description: 'Digital abstract art collection for gallery exhibition',
    coverImage: 'https://images.pexels.com/photos/23191211/pexels-photo-23191211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 203,
    lastUpdated: '2026-09-10T13:30:00Z',
    owner: 'Himanshu',
    storage: '3.6 GB',
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'proj-6',
    name: 'Fashion Campaign',
    description: 'High-end fashion editorial for spring collection',
    coverImage: 'https://images.pexels.com/photos/34921744/pexels-photo-34921744.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 178,
    lastUpdated: '2026-09-09T16:15:00Z',
    owner: 'Himanshu',
    storage: '3.2 GB',
    color: 'from-indigo-500 to-blue-600',
  },
  {
    id: 'proj-7',
    name: 'Product Photography',
    description: 'Professional product shots for luxury brand clients',
    coverImage: 'https://images.pexels.com/photos/28481966/pexels-photo-28481966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 321,
    lastUpdated: '2026-09-08T10:00:00Z',
    owner: 'Himanshu',
    storage: '5.8 GB',
    color: 'from-violet-500 to-cyan-600',
  },
  {
    id: 'proj-8',
    name: 'Marketing Campaign',
    description: 'Multi-platform advertising assets for B2B SaaS startup',
    coverImage: 'https://images.pexels.com/photos/13568045/pexels-photo-13568045.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 89,
    lastUpdated: '2026-09-07T14:30:00Z',
    owner: 'Himanshu',
    storage: '1.4 GB',
    color: 'from-sky-500 to-indigo-600',
  },
  {
    id: 'proj-9',
    name: 'Sci-Fi Universe',
    description: 'Concept art for upcoming sci-fi novel illustrations',
    coverImage: 'https://images.pexels.com/photos/8474976/pexels-photo-8474976.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 145,
    lastUpdated: '2026-09-06T11:20:00Z',
    owner: 'Himanshu',
    storage: '2.5 GB',
    color: 'from-blue-500 to-purple-600',
  },
  {
    id: 'proj-10',
    name: 'Portrait Collection',
    description: 'Artistic portrait series with diverse styles and moods',
    coverImage: 'https://images.pexels.com/photos/5611592/pexels-photo-5611592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    imageCount: 267,
    lastUpdated: '2026-09-05T09:45:00Z',
    owner: 'Himanshu',
    storage: '4.7 GB',
    color: 'from-rose-500 to-pink-600',
  },
];

export const MOCK_BATCH_JOBS: BatchJob[] = [
  {
    id: 'batch-1',
    name: 'Product Catalog Q4 2026',
    status: 'processing',
    total: 512,
    completed: 384,
    failed: 3,
    processing: 8,
    model: 'PixelForge Pro',
    credits: 4096,
    creditsUsed: 3072,
    startedAt: '2026-09-14T08:00:00Z',
    eta: '32 min',
    prompts: ['Product on white background', 'Lifestyle shot', 'Detail macro'],
    outputImages: [],
  },
  {
    id: 'batch-2',
    name: 'Social Media Pack — September',
    status: 'completed',
    total: 256,
    completed: 256,
    failed: 0,
    processing: 0,
    model: 'PixelForge Fast',
    credits: 1024,
    creditsUsed: 1024,
    startedAt: '2026-09-13T14:30:00Z',
    eta: 'Completed',
    prompts: ['Instagram story', 'Facebook banner', 'Twitter header'],
    outputImages: [],
  },
  {
    id: 'batch-3',
    name: 'Character Variations — Hero Set',
    status: 'paused',
    total: 128,
    completed: 64,
    failed: 2,
    processing: 0,
    model: 'Flux Pro',
    credits: 2048,
    creditsUsed: 1024,
    startedAt: '2026-09-12T10:00:00Z',
    eta: 'Paused',
    prompts: ['Hero character front view', 'Side view', 'Action pose'],
    outputImages: [],
  },
  {
    id: 'batch-4',
    name: 'YouTube Thumbnails — Batch 07',
    status: 'completed',
    total: 48,
    completed: 48,
    failed: 1,
    processing: 0,
    model: 'Cinematic XL',
    credits: 576,
    creditsUsed: 576,
    startedAt: '2026-09-11T16:00:00Z',
    eta: 'Completed',
    prompts: ['Tech review thumbnail', 'Gaming thumbnail', 'Tutorial thumbnail'],
    outputImages: [],
  },
  {
    id: 'batch-5',
    name: 'Architecture Renders — Downtown Project',
    status: 'failed',
    total: 64,
    completed: 28,
    failed: 36,
    processing: 0,
    model: 'PixelForge Flux Pro',
    credits: 1024,
    creditsUsed: 448,
    startedAt: '2026-09-10T09:00:00Z',
    eta: 'Failed',
    prompts: ['Building exterior', 'Interior lobby', 'Aerial view'],
    outputImages: [],
  },
  {
    id: 'batch-6',
    name: 'Fashion Lookbook — Winter 2026',
    status: 'queued',
    total: 320,
    completed: 0,
    failed: 0,
    processing: 0,
    model: 'Realistic Vision',
    credits: 3200,
    creditsUsed: 0,
    startedAt: '',
    eta: 'Queued',
    prompts: ['Winter outfit', 'Accessories focus', 'Full body shot'],
    outputImages: [],
  },
  {
    id: 'batch-7',
    name: 'Marketing Creatives — Startup Launch',
    status: 'completed',
    total: 96,
    completed: 96,
    failed: 0,
    processing: 0,
    model: 'PixelForge Pro',
    credits: 768,
    creditsUsed: 768,
    startedAt: '2026-09-09T11:00:00Z',
    eta: 'Completed',
    prompts: ['Hero banner', 'Feature icon', 'Social ad'],
    outputImages: [],
  },
  {
    id: 'batch-8',
    name: 'Abstract Art — Gallery Collection',
    status: 'completed',
    total: 200,
    completed: 200,
    failed: 0,
    processing: 0,
    model: 'Flux Dev',
    credits: 4000,
    creditsUsed: 4000,
    startedAt: '2026-09-08T13:00:00Z',
    eta: 'Completed',
    prompts: ['Abstract composition', 'Color study', 'Geometric pattern'],
    outputImages: [],
  },
  {
    id: 'batch-9',
    name: 'E-commerce Backgrounds',
    status: 'processing',
    total: 150,
    completed: 45,
    failed: 0,
    processing: 5,
    model: 'PixelForge Fast',
    credits: 600,
    creditsUsed: 180,
    startedAt: '2026-09-14T09:30:00Z',
    eta: '1h 15min',
    prompts: ['Studio white', 'Lifestyle kitchen', 'Outdoor natural'],
    outputImages: [],
  },
  {
    id: 'batch-10',
    name: 'Portrait Series — Diversity Collection',
    status: 'completed',
    total: 180,
    completed: 180,
    failed: 2,
    processing: 0,
    model: 'Realistic Vision',
    credits: 1800,
    creditsUsed: 1800,
    startedAt: '2026-09-07T10:00:00Z',
    eta: 'Completed',
    prompts: ['Natural light portrait', 'Studio portrait', 'Environmental portrait'],
    outputImages: [],
  },
];

export const MOCK_MODELS: AIModel[] = [
  {
    id: 'model-1',
    name: 'PixelForge Flux Pro',
    description: 'Our most advanced model with unparalleled photorealism and creative range. Best for commercial and professional work.',
    version: '3.2.1',
    speed: 'slow',
    quality: 'ultra',
    costPerImage: 8,
    tags: ['photorealistic', 'cinematic', 'commercial'],
    previewImage: 'https://images.pexels.com/photos/8107821/pexels-photo-8107821.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    recommended: true,
  },
  {
    id: 'model-2',
    name: 'PixelForge Pro',
    description: 'Premium quality generation with excellent prompt adherence and versatility. The go-to model for most use cases.',
    version: '2.8.4',
    speed: 'medium',
    quality: 'high',
    costPerImage: 6,
    tags: ['versatile', 'high-quality', 'accurate'],
    previewImage: 'https://images.pexels.com/photos/10109585/pexels-photo-10109585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'model-3',
    name: 'PixelForge Fast',
    description: 'Lightning-fast generation optimized for high-volume workflows. Great quality at incredible speed.',
    version: '2.1.0',
    speed: 'fast',
    quality: 'standard',
    costPerImage: 2,
    tags: ['fast', 'batch', 'efficient'],
    previewImage: 'https://images.pexels.com/photos/30547578/pexels-photo-30547578.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'model-4',
    name: 'Flux Pro',
    description: 'Black Forest Labs flagship model. Exceptional detail, creative freedom, and artistic expression.',
    version: '1.1.0',
    speed: 'slow',
    quality: 'ultra',
    costPerImage: 10,
    tags: ['artistic', 'detail', 'creative'],
    previewImage: 'https://images.pexels.com/photos/13568045/pexels-photo-13568045.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    new: true,
  },
  {
    id: 'model-5',
    name: 'Flux Dev',
    description: 'Open weights research model. Maximum control over generation with advanced parameter tuning.',
    version: '1.0.0',
    speed: 'slow',
    quality: 'ultra',
    costPerImage: 12,
    tags: ['research', 'advanced', 'control'],
    previewImage: 'https://images.pexels.com/photos/30767251/pexels-photo-30767251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'model-6',
    name: 'Realistic Vision',
    description: 'Hyper-realistic human portraits and photography. The best model for faces, people, and fashion.',
    version: '5.1.0',
    speed: 'medium',
    quality: 'high',
    costPerImage: 7,
    tags: ['portraits', 'realistic', 'fashion'],
    previewImage: 'https://images.pexels.com/photos/34921744/pexels-photo-34921744.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'model-7',
    name: 'Cinematic XL',
    description: 'Cinematic-quality renders with dramatic lighting and movie-grade compositions.',
    version: '1.5.0',
    speed: 'slow',
    quality: 'ultra',
    costPerImage: 9,
    tags: ['cinematic', 'dramatic', 'film'],
    previewImage: 'https://images.pexels.com/photos/8474976/pexels-photo-8474976.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
  {
    id: 'model-8',
    name: 'Illustration Pro',
    description: 'Vector-quality illustrations and digital art. Painterly styles, concept art, and fine art aesthetics.',
    version: '2.3.0',
    speed: 'medium',
    quality: 'high',
    costPerImage: 5,
    tags: ['illustration', 'concept-art', 'painting'],
    previewImage: 'https://images.pexels.com/photos/23191211/pexels-photo-23191211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tmpl-1',
    name: 'Product Hero Shot',
    description: 'Premium product photography with clean background',
    prompt: 'Premium product photography of {{product_name}}, placed on {{background}}, {{lighting}} lighting, ultra detailed, 8k resolution, commercial photography',
    negativePrompt: 'blurry, low quality, distorted, amateur',
    model: 'PixelForge Pro',
    resolution: '2048 × 2048',
    aspectRatio: '1:1',
    style: 'Product Photography',
    category: 'E-commerce',
    previewImage: 'https://images.pexels.com/photos/36339062/pexels-photo-36339062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 8420,
    rating: 4.9,
  },
  {
    id: 'tmpl-2',
    name: 'YouTube Thumbnail',
    description: 'Attention-grabbing cinematic thumbnails',
    prompt: 'Cinematic YouTube thumbnail, {{subject}}, dramatic lighting, vibrant colors, 16:9 composition, high contrast, professional',
    negativePrompt: 'boring, low contrast, cluttered',
    model: 'Cinematic XL',
    resolution: '1536 × 864',
    aspectRatio: '16:9',
    style: 'Cinematic',
    category: 'Content',
    previewImage: 'https://images.pexels.com/photos/10109585/pexels-photo-10109585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 6284,
    rating: 4.8,
  },
  {
    id: 'tmpl-3',
    name: 'Portrait Photography',
    description: 'Studio-quality portrait with professional lighting',
    prompt: 'Professional portrait of {{subject}}, {{lighting}} studio lighting, {{background}} background, 85mm lens, shallow depth of field, photorealistic',
    negativePrompt: 'distorted face, extra fingers, artifacts, unrealistic',
    model: 'Realistic Vision',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    style: 'Photorealistic',
    category: 'Photography',
    previewImage: 'https://images.pexels.com/photos/5611592/pexels-photo-5611592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 12840,
    rating: 4.9,
  },
  {
    id: 'tmpl-4',
    name: 'Cyberpunk Scene',
    description: 'Neon-lit cyberpunk cityscapes and characters',
    prompt: 'Cyberpunk {{subject}}, neon lights, rain-slicked streets, futuristic city, volumetric fog, cinematic composition, ultra detailed',
    negativePrompt: 'daytime, natural, rustic, vintage',
    model: 'PixelForge Flux Pro',
    resolution: '1536 × 1024',
    aspectRatio: '16:9',
    style: 'Sci-Fi',
    category: 'Art',
    previewImage: 'https://images.pexels.com/photos/8107821/pexels-photo-8107821.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 9156,
    rating: 4.7,
  },
  {
    id: 'tmpl-5',
    name: 'Instagram Post',
    description: 'Square-format lifestyle content for social media',
    prompt: 'Instagram lifestyle photo of {{subject}}, {{aesthetic}} aesthetic, golden hour lighting, warm tones, magazine quality',
    negativePrompt: 'dark, gloomy, amateur, oversaturated',
    model: 'PixelForge Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    style: 'Photorealistic',
    category: 'Social Media',
    previewImage: 'https://images.pexels.com/photos/34921744/pexels-photo-34921744.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 15230,
    rating: 4.8,
  },
  {
    id: 'tmpl-6',
    name: 'Architectural Visualization',
    description: 'Photorealistic building and interior renders',
    prompt: 'Architectural visualization of {{building_type}}, modern design, {{time_of_day}}, {{weather}}, ultra photorealistic, professional render',
    negativePrompt: 'cartoonish, old, deteriorated, messy',
    model: 'Cinematic XL',
    resolution: '2048 × 1152',
    aspectRatio: '16:9',
    style: 'Architecture',
    category: 'Architecture',
    previewImage: 'https://images.pexels.com/photos/2058172/pexels-photo-2058172.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 3720,
    rating: 4.9,
  },
  {
    id: 'tmpl-7',
    name: 'Fantasy Landscape',
    description: 'Epic fantasy world-building environments',
    prompt: 'Epic fantasy landscape, {{environment}}, magical atmosphere, dramatic sky, detailed foreground elements, concept art style',
    negativePrompt: 'modern, contemporary, urban, realistic',
    model: 'Flux Pro',
    resolution: '2048 × 1152',
    aspectRatio: '16:9',
    style: 'Fantasy',
    category: 'Art',
    previewImage: 'https://images.pexels.com/photos/13568045/pexels-photo-13568045.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 7640,
    rating: 4.8,
  },
  {
    id: 'tmpl-8',
    name: 'Abstract Art',
    description: 'Bold abstract compositions for digital collections',
    prompt: 'Abstract digital art, {{color_palette}} color palette, {{style}} style, dynamic composition, high contrast, gallery quality',
    negativePrompt: 'realistic, figurative, literal, plain',
    model: 'Illustration Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    style: 'Abstract',
    category: 'Art',
    previewImage: 'https://images.pexels.com/photos/23191211/pexels-photo-23191211.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 4980,
    rating: 4.6,
  },
  {
    id: 'tmpl-9',
    name: 'Fashion Campaign',
    description: 'Luxury fashion editorials for brand campaigns',
    prompt: 'Luxury fashion editorial, {{model_description}}, wearing {{outfit_description}}, {{location}}, professional fashion photography',
    negativePrompt: 'casual, amateur, low quality, overexposed',
    model: 'Realistic Vision',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    style: 'Fashion',
    category: 'Fashion',
    previewImage: 'https://images.pexels.com/photos/33714925/pexels-photo-33714925.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 5830,
    rating: 4.7,
  },
  {
    id: 'tmpl-10',
    name: 'Book Cover Design',
    description: 'Eye-catching book covers for fiction and non-fiction',
    prompt: 'Professional book cover design for {{genre}} book titled {{title}}, {{mood}} atmosphere, compelling artwork, typographic space',
    negativePrompt: 'text, low quality, generic, amateur',
    model: 'PixelForge Flux Pro',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    style: 'Concept Art',
    category: 'Publishing',
    previewImage: 'https://images.pexels.com/photos/207130/pexels-photo-207130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 2940,
    rating: 4.8,
  },
  {
    id: 'tmpl-11',
    name: 'Ad Creative',
    description: 'High-converting digital advertising visuals',
    prompt: 'Marketing advertisement for {{product}}, {{value_proposition}}, clean design, professional, attention-grabbing visual',
    negativePrompt: 'cluttered, cheap, amateur, off-brand',
    model: 'PixelForge Pro',
    resolution: '1024 × 1024',
    aspectRatio: '1:1',
    style: 'Commercial',
    category: 'Marketing',
    previewImage: 'https://images.pexels.com/photos/28481966/pexels-photo-28481966.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 11240,
    rating: 4.7,
  },
  {
    id: 'tmpl-12',
    name: 'Character Concept Art',
    description: 'Detailed character designs for games and animation',
    prompt: 'Character concept art, {{character_description}}, {{art_style}} style, full body view, detailed design sheet, professional illustration',
    negativePrompt: 'blurry, low detail, amateur, inconsistent',
    model: 'Illustration Pro',
    resolution: '1024 × 1536',
    aspectRatio: '2:3',
    style: 'Concept Art',
    category: 'Gaming',
    previewImage: 'https://images.pexels.com/photos/8108412/pexels-photo-8108412.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    usageCount: 6720,
    rating: 4.9,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'notif-1', type: 'success', title: 'Batch job completed', message: 'Product Catalog Q4 2026 has finished — 509/512 images generated', time: '2 min ago', read: false, icon: 'CheckCircle' },
  { id: 'notif-2', type: 'success', title: 'Image generated', message: 'Your generation "Futuristic cyberpunk city" is ready', time: '8 min ago', read: false, icon: 'Image' },
  { id: 'notif-3', type: 'warning', title: 'Credits running low', message: 'You have 420 credits remaining. Consider upgrading your plan.', time: '1 hr ago', read: false, icon: 'AlertTriangle' },
  { id: 'notif-4', type: 'info', title: 'New model available', message: 'Flux Pro v1.2.0 is now available with improved photorealism', time: '3 hrs ago', read: true, icon: 'Sparkles' },
  { id: 'notif-5', type: 'success', title: 'Export completed', message: '256 images from Social Media Pack have been zipped and are ready to download', time: '5 hrs ago', read: true, icon: 'Download' },
  { id: 'notif-6', type: 'success', title: 'Payment successful', message: 'Your Pro plan subscription has been renewed — 10,000 credits added', time: '1 day ago', read: true, icon: 'CreditCard' },
  { id: 'notif-7', type: 'info', title: 'Team member joined', message: 'Maya Chen has accepted the invitation and joined your team', time: '1 day ago', read: true, icon: 'UserPlus' },
  { id: 'notif-8', type: 'error', title: 'Generation failed', message: 'Architecture Renders — Downtown Project partially failed due to model timeout', time: '2 days ago', read: true, icon: 'AlertCircle' },
  { id: 'notif-9', type: 'success', title: 'Upscale complete', message: '12 images have been upscaled to 4K resolution', time: '2 days ago', read: true, icon: 'Maximize' },
  { id: 'notif-10', type: 'info', title: 'Storage notice', message: 'Your storage is at 76% capacity. Consider cleaning up old generations.', time: '3 days ago', read: true, icon: 'HardDrive' },
  { id: 'notif-11', type: 'success', title: 'Template saved', message: '"Product Hero Shot v2" has been saved to your templates', time: '3 days ago', read: true, icon: 'BookmarkCheck' },
  { id: 'notif-12', type: 'info', title: 'Scheduled maintenance', message: 'Brief maintenance window on Sept 16 at 3:00 AM UTC. Estimated 10 min downtime.', time: '4 days ago', read: true, icon: 'Wrench' },
  { id: 'notif-13', type: 'success', title: 'API key created', message: 'New API key "Production v2" has been created successfully', time: '5 days ago', read: true, icon: 'Key' },
  { id: 'notif-14', type: 'success', title: 'Background removal complete', message: 'Backgrounds removed from 48 product images', time: '6 days ago', read: true, icon: 'Eraser' },
  { id: 'notif-15', type: 'info', title: 'Feature release', message: 'New Outpainting feature is now available in the Image Editor', time: '1 week ago', read: true, icon: 'Stars' },
];

export const MOCK_TEAM: TeamMember[] = [
  { id: 'user-1', name: 'Himanshu Sharma', email: 'himanshu@pixelforge.ai', role: 'owner', avatar: 'HS', joinedAt: '2026-01-01', lastActive: '2 min ago', imagesGenerated: 8420 },
  { id: 'user-2', name: 'Maya Chen', email: 'maya@pixelforge.ai', role: 'admin', avatar: 'MC', joinedAt: '2026-02-14', lastActive: '1 hr ago', imagesGenerated: 3240 },
  { id: 'user-3', name: 'Jordan Rivera', email: 'jordan@pixelforge.ai', role: 'editor', avatar: 'JR', joinedAt: '2026-03-08', lastActive: '3 hrs ago', imagesGenerated: 1840 },
  { id: 'user-4', name: 'Alex Kim', email: 'alex@pixelforge.ai', role: 'editor', avatar: 'AK', joinedAt: '2026-04-22', lastActive: 'Yesterday', imagesGenerated: 920 },
  { id: 'user-5', name: 'Sophie Laurent', email: 'sophie@pixelforge.ai', role: 'viewer', avatar: 'SL', joinedAt: '2026-05-30', lastActive: '3 days ago', imagesGenerated: 0 },
  { id: 'user-6', name: 'Priya Nair', email: 'priya@pixelforge.ai', role: 'editor', avatar: 'PN', joinedAt: '2026-06-18', lastActive: '1 week ago', imagesGenerated: 560 },
];

export const MOCK_API_KEYS: ApiKey[] = [
  { id: 'key-1', name: 'Production API', key: 'pf_prod_sk_*********************8f2a', createdAt: '2026-08-01', lastUsed: '2 min ago', requestCount: 48420, status: 'active', permissions: ['generate', 'batch', 'gallery', 'projects'] },
  { id: 'key-2', name: 'Development API', key: 'pf_dev_sk_*********************3c9b', createdAt: '2026-07-15', lastUsed: '1 day ago', requestCount: 12840, status: 'active', permissions: ['generate', 'gallery'] },
  { id: 'key-3', name: 'Staging API', key: 'pf_stg_sk_*********************7e4d', createdAt: '2026-06-20', lastUsed: '1 week ago', requestCount: 3210, status: 'active', permissions: ['generate', 'batch'] },
  { id: 'key-4', name: 'Legacy Integration', key: 'pf_prod_sk_*********************1a8c', createdAt: '2026-03-10', lastUsed: '2 months ago', requestCount: 28940, status: 'revoked', permissions: ['generate'] },
];

export const USAGE_STATS = {
  totalImages: 12842,
  monthImages: 2418,
  batchJobs: 86,
  credits: 8420,
  storage: '38.4 GB',
  successRate: 98.7,
  monthlyData: [
    { month: 'Apr', images: 1240, credits: 8680 },
    { month: 'May', images: 1580, credits: 11060 },
    { month: 'Jun', images: 1920, credits: 13440 },
    { month: 'Jul', images: 2180, credits: 15260 },
    { month: 'Aug', images: 2350, credits: 16450 },
    { month: 'Sep', images: 2418, credits: 16926 },
  ],
  dailyData: [
    { day: 'Mon', images: 312 },
    { day: 'Tue', images: 428 },
    { day: 'Wed', images: 384 },
    { day: 'Thu', images: 502 },
    { day: 'Fri', images: 461 },
    { day: 'Sat', images: 188 },
    { day: 'Sun', images: 143 },
  ],
};
